#!/usr/bin/python
import sys,predict
if __name__=="__main__":
	seq="MGSGPRGALSLLLLLLAPPSRPAAGCPAPCSCAGTLVDCGRRGLTWASLPTAFPVDTTELVLTGNNLTALPPGLLDALPALRTAHLGANPWRCDCRLVPLRAWLAGRPERAPYRDLRCVAPPALRGRLLPYLAEDELRAACAPGPLCWGALAAQLALLGLGLLHALLLVLLLCRLRRLRARARARAAARLSLTDPLVAERAGTDES"
	name="kuan"
	p=predict.PhosphoRice(SeqName=name,Seq=seq)
	r=p.ScanSite("High")
	print r
